# Network and packets data
SERVER_PORT = 55555
HEADER_SIZE = 4
MAX_USERNAME_LEN = 16
AUTH_HASH_LEN = 32

# Client -> server
C_AUTH_CHALLENGE = 1
C_PLAY_REQUEST = 2
C_MOVE_PAWN = 3
C_BLOCK_TILE = 4
C_DISCONNECT = 5

# Server -> client
S_AUTH_RESPONSE = 6
S_LOBBY_LIST = 7
S_WAITING_OPPONENT = 8
S_MATCH_FOUND = 9
S_GAME_STATE = 10
S_YOUR_TURN = 11
S_INVALID_MOVE = 12
S_GAME_OVER = 13
S_OPPONENT_DISCONNECTED = 14

S_STATUS_FAIL = 15
S_STATUS_SUCCESS = 16
S_STATUS_CREATED = 17