# Network and packets data
SERVER_PORT = 55555
HEADER_SIZE = 4
MAX_USERNAME_LEN = 16
AUTH_HASH_LEN = 32

# Client -> server
C_AUTH_CHALLENGE = 1
C_PLAY_REQUEST = 2
C_MOVE_PAWN = 3
C_BLOCK_TILE = 4
C_DISCONNECT = 5
C_GET_PLAYER_LIST = 6
C_CHANGE_PASSWORD = 7

# Server -> client
S_AUTH_RESPONSE = 10
S_LOBBY_LIST = 11
S_WAITING_OPPONENT = 12
S_MATCH_FOUND = 13
S_GAME_STATE = 14
S_YOUR_TURN = 15
S_INVALID_MOVE = 16
S_GAME_OVER = 17
S_OPPONENT_DISCONNECTED = 18
S_PLAYER_LIST = 19
S_CHANGE_PASSWORD_RESPONSE = 20

S_STATUS_FAIL = 50
S_STATUS_SUCCESS = 51
S_STATUS_CREATED = 52

# Game over result codes
GAME_RESULT_WIN = 1
GAME_RESULT_LOSS = 2
GAME_RESULT_FORFEIT_WIN = 3
GAME_RESULT_FORFEIT_LOSS = 4

# Password change response codes
PASSWORD_CHANGE_SUCCESS = 1
PASSWORD_CHANGE_WRONG_OLD = 2
PASSWORD_CHANGE_ERROR = 3